### ISSUE TITLE
Failing on Travis

### ISSUE THREAD

**Issue by sir-dunxalot** [kategengler/ember-try#27]
I updated an addon's test suite and the build began failing on Travis with the following error:

```
The command "ember try $EMBER_TRY_SCENARIO test" exited with 1.
```

The test suite is passing locally. I have replicated the issue with versions 0.0.6 and 0.0.7 of this addon.

Is this a problem on your end or mine?

Thanks!

**Comment by sir-dunxalot** [comment]
Travis.yml file:

```
---
language: node_js
node_js:
  - "0.12"

sudo: false

cache:
  directories:
    - node_modules

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - bower install

script:
  - ember try $EMBER_TRY_SCENARIO test
```
